ViewPoint = {
    "背后视角": "from behind",
    "高位视角": "from above",
    "侧边视角": "from side",
    "背后焦点": "back focus",
    "臀部焦点": "hip focus",
    "人物面朝远方(背对)": "facing away",
    "侧脸": "profile",
    "第一人称": "first-person view",
    "主观视角": "pov",
    "手主观视角": "pov hands",
    "三视图进阶": "concept art",
    "多视图": "multiple views",
    "新房45度(By 姓符的绅士)":
        "looking at viewer,(from side:1.2),( head tilt:1.65),(leaning_back:1.25)",
    "男性焦点": "male focus",
    "女性焦点": "female focus",
    "电影镜头": "cinematic angle",
    "侧下": "from the Side below Black silk",
    "锐聚焦": "sharp focus",
    "正面面对": "straight-on",
    "三视图": "three sided view",
    "pp焦点": "ass focus",
    "低位视角": "from below",
    "胯部主观视角": "pov crotch",
    "足部焦点": "foot focus",
}
PaintScope = {
    "全身": "full body",
    "人物超出框": "out of frame",
    "头超出框": "head out of frame",
    "足超出框": "feet out of frame",
    "上半身": "upper body",
    "下半身": "lower body",
    "躯干下剪裁": "cropped torso upper body",
    "肩下剪裁": "cropped shoulders",
    "手臂下剪裁": "cropped arms",
    "腿下剪裁": "cropped legs",
    "牛仔特写": "cowboy shot",
    "人像": "portrait",
    "特写": "close-up",
    "自拍": "selfiemirror",
    "抱枕": "dakimakura",
    "表情表": "expressions",
    "对称": "symmetrical",
    "镀金边框": "gilt border",
    "Ally ahijah": "Ally ahijah  Powder coat  The blue eye",
    "超高分辨率出图": "incredibly_absurdres",
    "光线追踪": "ray tracing",
    "苏联红军": "red Soviet",
    "萌萌": "pleated skirt,heterochromia, ukiyo-e,poncho",
    "月夜": "loli girl moon night light lake glass",
    "Test": "Blue hair girl T-shirt short pants long hair no glasses ",
    "插入画面": "cut-in",
    "游乐园海报": "amusement park,advertise,poster"
}
OpticAngle = {
    "斜角镜头": "dutch angle",
    "强烈镜头": "intense angle ",
    "电影镜头": "cinematic angle ",
    "戏剧性镜头": "dramatic angle ",
    "动态镜头": "dynamic angle ",
    "远景": "wide shot",
    "透视": "perspective",
    "正前缩距": "foreshortening",
    "鱼眼": "fisheye",
    "颠倒": "upside-down",
    "运动模糊 ": "motion blur",
    "景深": "depth of field",
    "镜头光晕": "lens flare",
    "背光": "backlight",
    "电影角度": "cinematic angle",
    "高饱和度": "high saturation",
    "聚焦人物镜头": "lens 135mm,f1.8",
    "全景": "overall view",
    "超广角": "ultrawide shot"
}
Background = {
    "模糊背景": "blurry background",
    "简单背景": "simple background",
    "旭日纹背景": "sunburst background",
    "渐变背景": "gradient background",
    "缩放投影图层": "zoom layer",
    "背光": "backlighting",
    "投影阴影": "drop shadow",
    "轮廓线": "outline",
    "剪影": "silhouette",
    "白色背景": "white background",
    "五彩斑斓的星轨": "colorful startrails",
    "櫻花": "Cherry blossoms",
    "流星": "shooting star",
    "简单花纹背景": "Simple pattern background",
    "米色背景": "beige background",
    "空间背景": "space background",
    "城市背景": "cityscape",
    "散景": "bokeh",
    "机场背景": "airport background",
    "地牢背景": "dungeon background",
    "沙滩背景": "beach background",
    "飞翔的蝴蝶": "flying butterfly",
    "異世界奇幻城市": "Isekai cityscape",
    "详细背景": "detailed background",
    "烟花": "firework",
    "在床上": "on bed",
    "草坪": "lawn",
    "高山，山脉": "alpine",
    "战场": "battlefield",
    "红月，血月": "red moon",
    "农场": "farm",
    "背景虚化": "blur_background",
    "雨": "rain",
    "电流": "electricity",
    "蓝天白云": "blue sky with clouds",
    "草地": "grassland",
    "新月": "crescent",
    "雪地": "snowfield",
    "雪花": "snowflakes",
    "极光": "aurora",
    "漂浮的白色羽毛": "floating white feathers",
    "闪烁的星星": "glinting stars",
    "繁星": "starry sky,clusters of stars",
    "紫罗兰": "violet",
    "散落樱花": "floating sakura",
    "星空": "starry sky",
    "雪 by czz": "snow",
    "赛博朋克": "cyberpunk, city, kowloon, rain",
    "森林": "forest",
    "海水": "sea",
    "学校": "lovely",
    "雨滴（效果极好）": "raindrop",
    "萤火虫": "firefly",
    "飘散的花瓣": "petals floating in the wind",
    "赛车场": "Racing Track",
    "浴室": "bathroom",
    "太空": "space",
    "城市风景": "cityscape",
    "摩天楼": "skyscraper",
    "废墟": "ruins",
    "鸟居": "torii",
    "田园": "field",
    "海洋": "ocean",
    "海边": "beach",
    "湖泊": "lake",
    "河流": "river",
    "温泉": "onsen",
    "室外": "outdoors",
    "室内": "indoors",
    "塌塌米": "tatami",
    "无人": "no humans",
    "教堂": "church",
    "繁花草甸": "flowers meadows",
    "商店": "shop",
    "喷泉": "fountain",
    "阿尔卑斯山脉": "Alps",
    "街道": "street",
    "赛博朋克城市": "cyberpunk city",
    "古风建筑": "chinese style architecture",
    "神社": "gohei",
    "繁华都市": "Bustling city",
    "实验室": "laboratory",
    "咖啡馆": "coffee house",
    "宿舍": "dormitory",
    "健身房": "gym",
    "厨房": "kitchen",
    "寺庙": "temple",
    "博物馆": "museum",
    "图书馆": "library",
    "监狱": "prison",
    "轮机舱": "engine room",
    "配电房": "electrical room",
    "服务器机房": "server room",
    "栏杆": "handrail",
    "霓虹灯": "neon lights",
    "路灯": "street lamp",
    "道路": "road",
    "贫民窟": "shanty town/slum",
    "地下室": "basement",
    "梦幻之森(虚幻感.光粒子幽静)": "Dreamy forest",
    "美术室": "art room",
    "仓库": "warehouse",
    "哥特式建筑": "gothic architecture",
    "时钟背景": "clockbackground",
    "浴": "bathing",
    "饭店": "restaurant",
    "树屋": "treehouse",
    "法兰西": "modern,Europe",
    "工业化古建筑": "Industrial wind, Chinese architecture",
    "建筑废墟": "building_ruins",
    "山脉": "mountain",
    "卧室": "bedroom",
    "教室": "classroom",
    "楼梯": "stairs",
    "（教堂的）彩绘玻璃": "stained glass",
    "建筑物": "building architecture",
    "东亚建物": "east asian architecture",
    "西罗马建筑": "greco-roman architecture",
    "圣诞树": "christmas tree",
    "中国江南水乡风格": "China Jiangnan water town style",
    "落地窗": "French window",
    "齿轮": "gear",
    "大自然": "nature"
}
Style = {
    "提取高质量数据": "masterpiece",
    "高分辨率": "highres",
    "统一风格": "Unity Creations",
    "轮廓加深": "contour deepening",
    "纯色块": "flat color",
    "单色": "monochrome",
    "灰度": "greyscale",
    "高对比度度": "high contrast",
    "部分着色": "partially colored",
    "色差色失焦": "chromatic aberration",
    "Game CG": "game cg",
    "漫画": "comic",
    "动画截图": "capanime screencap",
    "素描": "sketch",
    "像素风": "pixel art",
    "Q版": "chibi",
    "新艺术运动(慕夏)": "art nouveau ",
    "现实的 ": "realistic",
    "复古风格": "retro artstyle",
    "1980风格": "1980s (style)",
    "1990风格": "1990s (style) ",
    "女神杂志": "megami magazine",
    "同人志风": "doujinshi doujin cover",
    "卡牌风": "card games",
    "逼真的": "photorealistic",
    "赛博朋克": "Cyberpunk",
    "高清壁纸": "extremely detailed CG unity 8k wallpaper",
    "Persona 5 风格":
        "official art, red background, flat color, partially colored, {persona 5}",
    "精确的几何形状": "Precise geometry",
    "线稿": "Line art",
    "塔罗牌风格": "tarot",
    "唯美主义": "Aestheticism Painting",
    "精细漫画插画": "detailed manga illustration",
    "原画": "artbook",
    "复杂的细节": "intricate detail",
    "折纸艺术": "{{{origami art}}}, paper art",
    "纸艺风格": "{{{paper Figure}}}, origami art, 3d",
    "fate stay night; saber": "fate stay night; saber",
    "轻小说插画风": "art of light novel",
    "杂志封面": "magazine cover",
    "水墨": "Ink wash painting",
    "浮世繪": " ukiyo-e",
    "平面着色": "flat shading",
    "色彩化": "colorful",
    "斯普拉遁": "{{splatoon}}",
    "浮世绘": "ukiyo-e",
    "矢量追踪": "vector tracing",
    "90年代": "90's",
    "水彩画": "watercolor",
    "剪影": "silhouette",
    "传统媒体": "traditional media",
    "描边": "outline",
    "水墨画": "ink and wash painting",
    "彩铅绘": "colored pencil drawing",
    "素描草图": "rough sketch",
    "抱枕": "dakimakura",
    "动漫截图": "anime screencap",
    "漫画书": "comic book",
    "杂志扫图": "magazine scan",
    "伪截图": "fake screenshot",
    "角色设定图": "character design",
    "官方图": "official art",
    "手办": "figure",
    "纸模": "papercraft",
    "体素画": "voxel art",
    "像素画": "pixel art",
    "四格漫画": "4koma",
    "苏维埃海报": "soviet poster",
    "海报": "poster",
    "OC渲染器": "octane render",
    "写实": "realistic",
    "平涂/平色": "flat color",
    "网点": "screentones",
    "单色画": "monochrome",
    "蒸汽波": "Vaporwave",
    "平涂": " flat color",
    "科幻风格": "science fiction",
    "立绘": "tachie",
    "游戏王": "Yu-Gi-Oh,kazuki takahashi",
    "墨水溅": "ink splashing",
    "p站风格": "pixiv id",
    "灰度图": "grayscale",
    "插图": "illustration",
    "草稿风": "{rough sketch}",
    "极简线条": "minimalist-lines",
    "暗色调": "Tenebrism",
    "蒸汽朋克风": "Steampunk",
    "线条艺术": "line art",
    "水墨动漫风": "Ink anime"
}
Media = {
    "照片": "photo (medium) ",
    "水彩": "watercolor (medium)",
    "油画 ": "oil painting (medium) ",
    "彩色铅笔": "colored pencil (medium) ",
    "铅笔画": "graphite (medium) ",
    "马克笔": "marker (medium)",
    "签字笔": "nib pen (medium)",
    "原子笔": "ballpoint pen (medium)",
    "丙烯颜料": "acrylic paint (medium)",
    "厚涂": "{photorealistic}, {painting}, {realistic}, {sketch}, {oil painting}",
    "水粉": "gouache",
    "湿画法水粉": "wet gouache",
    "工笔画（比起素描感觉更适合ink）": "meticulous painting",
    "禅绕": "Zentangle (medium)",
    "精致的反光和高玻璃护栏板": "delicate reflective and high glass guardrail board"
}
Subject = {
    "单女": "1girl",
    "单人": "solo",
    "两女": "2girls",
    "三人行": "threesome",
    "双子": "twins",
    "两男": "two boys",
    "多女": "multiple girls",
}
SubjectAdj = {
    "娇小的": "petite",
    # "百合": "yuri",
    "睡觉": "sleeping",
    # "异性": "hetero",
    "人鱼": "Mermaid",
    "机娘": "mecha girl",
    "女仆": "maid",
    "修女": "nun",
    "巫女": "miko",
    "福瑞（兽人）": "furry",
    "刀剑": "knife and sword",
    "忍者": "ninja",
    "龙娘": "dragon girl",
    "细腻的肌肉线条": "Delicate muscle lines",
    "拟人": "gijinka",
    "护士": "nurse",
    "日系兽人/萌系兽人": "kemono",
    "壮汉": "Strong man",
    "洛丽塔风格": "lolita fashion",
    "细腰": "slim waist",
    "美少女（By 自由夸克）": "bishoujo",
    # "成熟男性": "mature male",
    "狙击手": "profile",
    "吸血鬼": "vampire",
    "魅魔": "succubus",
    "女巫": "witch",
    "天使": "angel",
    "狐娘": "fox girl",
    # "下体突出（男性）": "bulge",
    "风精灵.希尔芙(精灵尖耳.白或绿发.薄纱蝶翼": "Sylph",
    "火妖.伊芙利特(不加其他修饰就是火焰恶魔": "Ifrit",
    "水精灵（肢体偏水化，整体偏蓝）": "water sprit",
    "马甲线": "linea alba",
    "机器人": "robot",
    "牧师": "priest",
    "公主": "princess",
    "人形机器人/机器仿生人（安卓）": "android",
    "miku": "(((hatsune miku)))",
    "假面骑士": "kamen rider",
    "黑化": "dark_persona",
    "肌肉": "muscle",
    "水精灵.温蒂尼（肤色偏蓝，鲛人耳朵，大量水元素）": "Undine",
    "熟女": "mature female",
    # "正太": "shota",
    "匀称的身材": "neat figure",
    "苗条的腰": "slender waist",
    "金刚芭比魔法战士": "muscle magician",
    "雪妖": "froslass",
    "魔法师": "enchanter",
    "油腻的皮肤": "shiny skin",
    "碧蓝航线（加了就变涩）": "azure lane",
    "完美的女体(全年龄段)": "Perfect female body",
    "恶魔": "demon",
    "青少年": "teenage",
    "日式辣妹": "grayu",
    "兔娘": "bunny girl",
    "犬娘（单独使用效果很弱）": "dog girl",
    "猫娘": "cat girl",
    # "小男孩": "Little Boy",
    "机械三件套（机械，机甲，金属）": "Machinery, metal, mech",
    "出汗": "sweat",
    "女神": "goddess",
    "当你想要一张福瑞图的时候你可能需要输入的词条": "furry,pokemon,no humans",
    "动物化（兽控类）": "animalization",
    "青春期": "adolescent",
    "蓝火与剑交织": "blue fire and sword interweave",
    "金属翅膀": "metal wings",
    "机械翅膀": "mechanical armor wings",
    "机器人女孩": "robot girl",
    "女性军人": "female soldier",
    "幼女": "infant",
    "女巨人": "giantess",
    "精灵": "elf",
    "处女": "virgin",
    "少女(By 匿名)": "young girl",
    "中式、中国风": "Chinese style",
    "人偶关节(建议适当提权)": "doll joints",
    # "美少年": "bishounen",
    "奶油版光滑的皮肤": "the creamy smooth skin"
}
Hair = {
    "呆毛": "ahoge",
    "齐刘海": "blunt_bangs",
    "卷发": "curly hair",
    "钻头卷/公主卷": "drill_hair",
    "包子头": "hair_bun",
    "包子头(两个)": "double_bun",
    "马尾": "ponytail",
    "短马尾": "short ponytail",
    "侧马尾": "side ponytail",
    "凌乱发型": "messy_hair",
    "姬发式": "hime_cut",
    "长鬓角": "payot",
    "波浪发型": "wavy_hair",
    "短发": "short hair",
    "长发": "long hair",
    "很长的头发": "very_long_hair",
    "没鼻子的": "no_nose",
    "尖牙": "fangs",
    "舌头": "tongue",
    "唾液": "saliva",
    "动物耳朵": "animal_ears",
    "狐狸耳朵": "fox_ears",
    "兔耳": "bunny_ears",
    "猫耳": "cat_ears",
    "狗耳": "dog_ears",
    "老鼠耳朵": "mouse_ears",
    "尖耳": "pointy_ears",
    "闪亮头发": "shiny hair",
    "金发": "blonde hair",
    "多色头发": "multicolored hair",
    "分色头发": "split-color hair",
    "渐变头发": "gradient hair",
    "条纹头发": "streaked hair",
    "尖端挑染": "colored tips",
    "彩色内毛": "colored inner hair",
    "蘑菇头": "bowl cut",
    "中长发": "medium hair",
    "妹妹头": "bob cut",
    "翘发": "flipped hair",
    "姬切": "hime cut",
    "低扎长发": "low-tied long hair",
    "高马尾": "high ponytail",
    "低马尾": "low ponytail",
    "前马尾": "front ponytail",
    "低双马尾": "low twintails",
    "短双马尾": "short twintails",
    "编织马尾辫": "braided ponytail",
    "折迭马尾辫": "folded ponytail",
    "单辫 ": "single braid",
    "低双辫": "low twin braids",
    "侧织辫": "side braid",
    "冠型织辫": "crown braid",
    "法式辫子": "french braid",
    "脏辫": "dreadlocks",
    "辫子刘海": "braided bangs",
    "发髻": "hair bun",
    "单发髻": "single hair bun",
    "双发髻": "double bun",
    "锥形发髻": "cone hair bun",
    "辫子髻": "braided bun",
    "甜甜圈发髻": "doughnut hair bun",
    "心型发髻": "heart hair bun ",
    "自然卷": "wavy hair",
    "钻发": "drill hair",
    "双钻发": "twin drills",
    "小环管卷发": "ringlets",
    "不对称浏海": "asymmetrical bangs",
    "齐浏海": "blunt bangs",
    "刘海遮眼": "hair over eyes",
    "刘海遮单眼": "hair over one eye",
    "分开浏海": "parted bangs",
    "扫浏海": "swept bangs",
    "眼间发": "hair between eyes",
    "耳前发": "sidelocks",
    "单耳前发": "single sidelock",
    "长耳前+短发": "short hair with long locks",
    "进气口(M毛)": "hair intakes",
    "侧发后梳(公主结)": "half updo",
    "头发后梳": "hair pulled back",
    "一侧绑发": "one side up",
    "双侧绑发": "two side up",
    "多绑头发": "multi-tied hair",
    "蝴蝶结发": "bow-shaped hair",
    "顶绑发": "topknot",
    "凌乱头发": "messy hair",
    "尖发动耳发": "pointy hair",
    "毛瓣": "hair flaps",
    "头发散落": "hair spread out",
    "天线毛": "antenna hair",
    "漂浮的头发": "floating hair",
    "直发": "straight hair",
    "鲍勃头（雷姆式）": "bob",
    "狼耳": "wolf ear fluff",
    "右边侧发": "right side temple hair",
    "左边侧发": "left side temple hair",
    "双侧发": "temple hairs",
    "双龙须刘海": "twin slut strands",
    "龙须刘海": "slut strands",
    "挑染": "streaked hair",
    "鲍伯头": "bob cut",
    "紫色头发（羽化前）": "purple_hair",
    "粉色头发（羽化前）": "pink_hair",
    "橙色头发": "Orange hair",
    "棕色头发（羽化前）": "brown_hair",
    "蓝色头发": "blue_hair",
    "黑色头发（羽化前）": "black hair",
    "水蓝色头发（羽化前）": "aqua_hair",
    "白发": "loli,white hair,girl,blue eye",
    "灰色杂乱长发": "grey_messy_long_hair",
    "栗子色头发": "Chestnut_hair",
    "两眼之间的头发": "hair between eyes",
    "中分头": "Split head",
    "长长的卷发": "long wavy curly hair",
    "披肩单马尾": "one side up hair",
    "披肩双马尾": "two side up hair",
    "团子头(和风)": "updo hair",
    "长到能拖地的头发(随缘生效)":
        "(very long hair),foot length hair,long hair to the ground",
    "魅魔萝莉": "loli red",
    "绿发": "green_hair",
    "不对称双马尾": "uneven twintails",

    "双辫子": "twin_braids",
    "两色头发 ": "two-tone hair",
    "露额头（没有刘海）": "To reveal the forehead",
    "动态头发": "Dynamic hair",
    "中分": "Medium score",
    "双麻花辫": "twin braids",
    "双马尾": "twintails",
    "麻花辫": "braid",
    "光头": "bareheaded",
    "刘海": "bangs",
    "粉棕色头发": "Pink_brown hair",
    "水下，使用于人物，如头发漂浮效果": "Underwater portrait",
    "及腰长发": "Waist_length_hair",
    "極短頭髮": "very short hair",
    "四马尾": "quad tails",
    "交叉刘海": "crossed bangs"
}
Color = {
    "银发/银眼": "silver_hair/silver_eyes",
    "灰发/灰眼": "grey_hair/red_eyes",
    "白发/白眼": "white_hair/white_eyes",
    "棕发/棕眼": "brown_hair/brown_eyes",
    "黑发/黑眼": "black_hair/black_eyes",
    "紫发/紫眼": "purple_hair/purple_eyes",
    "红发/红眼": "red_hair/red_eyes",
    "蓝发/蓝眼": "blue_hair/blue_eyes",
    "绿发/绿眼": "green_hair/green_eyes",
    "粉发": "pink_hair",
    "灰发紫眼": "gray hair purple eyes",
    "黑蓝色头发": "Black blue hair",
    "深棕色头发": "Dark brown hair",
    "希尔发色外黑内蓝": "Large area of cyan Pick dyeing",
    "浅紫发/浅紫眼": "lilac_hair/lilac_eyes",
    "白发/绿眼": "white_hair/green_eyes",
    "黑发": "black hair",
    "青色": "turquoise",
    "蓝眼": "blue_eyes",
    "黑发蓝瞳": "black_hair/blue_eyes",
    "宝石粉发": "crystal pink_hair",
    "白金发色": "platinum_hair",
    "银发": "Silver hair",
    "紫眼": "purple eyes",
    "水做的肌肤（碧蓝水色的皮肤颜色）": "Skin made of water",
    "水色头发（浅蓝）": "aqua_hair",
    "金发/蓝眼": "blonde_hair/blue_eyes",
    "红眼": "red eyes",
    "黑皮（女性）": "dark-skinned_female",
    "茶色瞳/发": "tawny eyes/tawny hair",
    "金发/金眼": "blonde_hair/yellow_eyes",
    "灰发": "grey_hair",
    "红发": "red_hair",
    "白发/蓝眼": "white_hair/blue_ey",
    "白发": "white_hair",
    "白发/蓝瞳": "white_hair/blonde_eyes",
    "银发/青眼": "silver_hair/cyan_eyes",
    "金发": "blonde_hair",
    "日烧色（晒黑）": "tan",
    "日烧痕迹（晒黑线）": "tanlines",
    "水色眼睛（浅蓝）": "aqua_eyes",
    "粉色眼睛": "pink_eyes",
    "绿眼": "green_eyes",
    "青眼": "cyan_eyes",
    "银眼": "silver_eyes",
    "白发/红瞳": "white_hair,red_eyes"
}
Head = {
    "看观众": "looking at viewer",
    "面对观众": "facing viewer",
    "看着另一个": "looking at another",
    "看侧边": "looking to the side",
    "不看镜头": "looking away",
    "回头看": "looking back",
    "往下看": "looking down",
    "往上看": "looking up",
    "遥望": "looking afar",
    "盯着": "staring",
    "对视": "eye contact",
    "斜视": "sideways glance",
    "开嘴": "parted lips",
    "开口": "open mouth",
    "闭嘴": "closed mouth",
    "吐舌": "tongue out",
    "舔嘴唇": "licking lips",
    "咬紧牙关": "clenched teeth",
    "微笑": "smile",
    "露齿笑": "grin",
    "坏笑": "evil smileevil grin",
    "得意笑": "smirk",
    "自鸣得意": "smug doyagao",
    "幸灾乐祸": "troll face ",
    "诱人的微笑": "seductive smile ",
    "呼吸": "breath",
    "摸头": "headpat",
    "哭哭": "crying",
    "张眼哭": "crying with eyes open",
    "脸贴脸": "cheek-to-cheek",
    "角": "horn",
    "呼吸急促": "heavy breathing",
    "狂气龇牙/坏笑": "crazy angry smile，clenched_teeth",
    "额头": "forehead",
    "一对角": "pair of horns",
    "鹿角": "antlers",
    "兽耳": "kemomimi",
    "兔子耳朵": "rabbit ears",
}
Pose = {
    "弓背": "arched back",
    "拉伸": "stretching",
    "躺着": "lying",
    "趴着": "on stomach",
    "侧躺": "on side",
    "四肢着地": "all fours",
    "双腿过头": "legs over head",
    "自拍": "selfie",
    "通过腿看": "looking through legs",
    "二郎腿": "crossed_legs",
    "跪姿": "kneel",
    "萝莉坐": "kneeling&setting on floor",
    "坐在地上": "sitting on the ground",
    "一字马": "standing split",
    "手臂在背后 ": "arms behind back ",
    "狗趴式": "doggystyle",
    "泡温泉": "half body under water",
    "趴着翘臀": "top-down_bottom-up",
    "開腳": "open your legs wide",
    "漏腋": "armpits",
    "战斗姿态": "fighting_stance",
    "坐在椅子上": "sitting on chair",
    "瑜伽": "yoga",
    "绝对空域（大腿三角）": "thigh gap",
    "骑马": "horse riding",
    "行走": "walk",
    "正骑乘": "girl on top",
    "祈祷": "pray",
    "翘PP": "top-down bottom-up",
    "抱膝": "huddle, clasp knees",
    "公主抱": "princess carry",
    "侧躺着": "Lie on your side",
    "抚摸": "groping",
    "撩起衣服": "clothes_lift",
    "盘腿坐": "indian style",
    "动态姿势": "dynamic pose",
    "敬礼": "salute",
    "平趴着": "prostrate, lie flat",
    "提裙": "Skirt lift",
    "蹲着": "squatting",
    "坐在车上": "sitting on car",
    "双手抱肩": "Put hands around shoulders",
    "托腮": "gill support",
    "张开腿": "spread legs",
    "掀裙子": "skirt_lift",
    "跨坐": "straddling",
    "舌吻": "French kiss, proper kiss",
    "坐在床上": "sitting on bed",
    "弯腰": "bent over",
    "抱胸/遮挡胸部": "hug self",
    "站立": "standing",
    "漂浮": "floating",
    "骑乘": "girl_on_top,straddling",
    "鸭子坐": "wariza",
    "踩踏（在......上）": "trampling",
    "胎儿姿势(身体卷缩着)": "fetal position",
    "坐在地上(似鸭子坐)": "w-sitting on the ground",
    "坐着": "sitting",
    "叉开着腿坐": "figure four sitting"
}
Hand = {
    "伸出双臂": "outstretched arms",
    "伸出单臂": "outstretched arm",
    "伸出单手": "outstretched hand",
    "伸手触及": "reaching",
    "张开双臂": "spread arms",
    "殭尸姿势": "zombie pose",
    "单抬臂": "arm up",
    "双抬臂": "arms up",
    "展示腋下": "presenting armpit",
    "手臂放头后": "arms behind head",
    "手臂放后面": "arms behind back",
    "双手叉腰 ": "hands on hips",
    "手放嘴上": "hand to own mouth",
    "手放脸上": "hand on own face",
    "抱自己的腿": "hugging own legs",
    "手臂支撑": "arm support",
    "拨头发": "hand in own hair",
    "双手拨头发": "hands in hair",
    "调整头发": "adjusting hair",
    "扎头发 ": "tying hair",
    "牵手": "holding hands",
    "手指相扣": "interlocked fingers",
    "双手相扣": "own hands clasped",
    "双手相合": "own hands together",
    "紧握双手": "clenched hands",
    "张开双手": "open hands",
    "张开手指 ": "spread fingers",
    "打手枪手势": "handjob gesture",
    "雙V手勢": "double peace hand",
    "用手指做出笑脸": "fingersmile",
    "手交叉于胸前": "arms crossed",
    "手镯": "Bracelet",
    "掰开": "hand on crotch",
    "隐藏手": "hidden hands",
    "拿着伞": "holding umbrella",
    "把手放在口袋里": "Put your hands in your pockets",
    "托腮": "chin",
    "精细手指": "detail fingers",
    "手放在口袋里": " hands in pockets",
    "嘘": "shushing"
}
Leg = {
    "XX夹腿间": "between legs",
    "手夹腿间": "hand between legs",
    "抬双腿": "legs up",
    "膝盖向上": "knees up",
    "膝到胸": "knees to chest",
    "内八": "pigeon-toed",
    "M字腿": "m legs",
    "足部屈曲": "plantar flexion",
    "伸展脚趾": "spread toes",
    "脚悬空": "feet up",
    "粗腿": "thick_thighs",
    "大屁股": "big ass",
    "绝对领域勒肉版": "skindentation",
    "屁股通过大腿可见": "ass visible through thighs",
    "黑丝jk": "jk face leg",
    "尾巴夹腿间": "tail between legs",
    "厚底带跟过膝长靴": "platform heel ((thigh boots))",
    "双膝并拢脚分开": "knees together feet apart",
    "细腿": "slim legs",
    "抬腿": "leg up",
    "双腿交叉": "crossed legs",
    "脚环": "anklet",
    "损坏了的过膝袜": "torn_thighhighs",
    "双腿分开": "legs apart",
    "双腿并拢": "knees together",
    "展示脚部": "presenting foot"
}
Face = {
    "脸红": "blush",
    "尴尬害羞": "embarrassed",
    "高潮": "orgasm",
    "恍惚放荡": "torogao",
    "酒醉": "drunk",
    "阿嘿颜": "ahegao",
    "干到傻": "fucked silly",
    "戏弄调戏脸": "naughty face",
    "皱眉蹙眼": "wince",
    "阴暗脸": "shaded face",
    "厌恶": "disgust",
    "恼火": "annoyed",
    "噘嘴": "pout",
    "紧张": "nervous",
    "困惑": "confused",
    "害怕": "scared",
    "疼痛": "pain",
    "尖叫": "screaming",
    "惊讶": "surprised",
    "脸色苍白 ": "turn pale",
    "悲伤": "sad",
    "忧郁": "gloom (expression) depressed",
    "叹息": "sigh",
    "想睡的": "sleepy",
    "认真": "serious",
    "皱眉": "frown",
    "V字眉 ": "v shaped eyebrows",
    "八字眉": "furrowed brow raised eyebrows",
    "挑眉": "raised eyebrow",
    "短眉": "short eyebrows",
    "浓眉": "thick eyebrows",
    "流口水": "drooling",
    "波浪嘴": "wavy mouth",
    "牙齿": "teeth",
    "上牙 ": "upper teeth",
    "鲨鱼牙": "sharp teeth",
    "咬紧牙关": "clenched teeth",
    "圆齿": "round teeth",
    "嘴虎牙": "skin fang",
    "舌头": "tongue",
    "口红": "lipstick",
    "尖耳朵": "pointy ears",
    "犄角": "horns",
    "微笑": "light smile",
    "露齿笑": "grin",
    "眼泪": "tears",
    "絡腮鬍": "Beard",
    "八字鬍": "mustache",
    "山羊鬚": "goatee",
    "张嘴": "open  mouth",
    "食物在脸上（by 冬日谎言）": "food on face",
    "被催眠的":
        "looking up,no pupils,empty eyes,drooling,messy_hair,open mouth",
    "面无表情": "clear face,expressionless",
    "下流的表情": "naughty_face",
    "唱歌": "singing sang.",
    "舔": "licking",
    "被催眠的（更新）":
        "looking up,no pupils,empty eyes,drooling,messy_hair,open  mouth,,glowing eyes,(half-closed eyes,),(expressionless),open  mouth",
    "冷淡的表情（可能需要与负面词cold搭配使用）": "cold attitude",
    "洋洋得意": "smug",
    "精致脸庞": "beautiful_face",
    "慌乱嘴型(也是艾草的嘴型)": "Open mouth indicating flustered",
    "无表情": "expressionless",
    "虎牙": "fang"
}
Eye = {
    "眼透头发": "eyes visible through hair",
    "单遮眼": "hair over one eye one eye covered",
    "绷带遮单眼": "bandage over one eye",
    "闭眼": "closed eyes",
    "闭单眼": "one eye closed",
    "半开眼": "half-closed eyes",
    "瞇眼": "squinting",
    "吊眼角": "tsurime",
    "下垂眼": "tareme",
    "上看的眼睛": "upturned eyes",
    "失神眼": "empty eyes",
    "三白眼": "sanpaku",
    "半开平线眼": "jitome",
    "斗鸡眼的": "cross-eyed",
    "不对称眼": "uneven eyes",
    "疯狂眼睛": "crazy eyes",
    "睁大眼睛": "wide-eyed",
    "发光眼睛": "glowing eyes",
    "圈圈眼": "ringed eyes",
    "收缩的瞳孔": "constricted pupils",
    "猫瞳": "slit pupils",
    "水平瞳孔": "horizontal pupils",
    "爱心瞳": "heart-shaped pupils",
    "符号瞳": "symbol-shaped pupils",
    "异色瞳": "heterochromia grey red",
    "没有瞳孔": "no pupils",
    "发亮瞳孔": "bright pupils",
    "眼睫毛": "eyelashes",
    "眼影": "eyeshadow",
    "眼线": "eyeliner",
    "渐变眼": "gradient eyes",
    "水汪汪的眼睛": "aquagradient eyes",
    "金色的瞳孔": "beautiful golden eyes",
    "有色巩膜（眼白）": "colored sclera",
    "圆眼": "round eyes",
    "猫眼（竖瞳）": "slit pupils",
    "半闭眼": "half-closed eyes",
    "爱心瞳孔": "heart-shaped_pupils",
    "精细的眼睛": "beautiful detailed eyes",
    "青色眼瞳": "Cyan eyes",
    "丹凤眼": "phoenix eye",
    "琉璃瞳孔": "Glazed pupils",
    "翻白眼": "rolling eyes"
}
Clothes = {
    "比基尼": "bikini",
    "系绳比基尼": "string bikini",
    "解开比基尼": "untied bikini",
    "前系带比基尼上着": "front-tie bikini top",
    "泳装": "swimsuit",
    "连体泳衣": "one-piece swimsuit",
    "学校泳衣": "school swimsuit",
    "竞赛泳衣": "competition swimsuit",
    "运动服": "sportswear",
    "排球服": "volleyball uniform",
    "旗袍": "china dress",
    "水手服": "white sailor dress",
    "布鲁玛": "buruma",
    "高领衬衫": "collared shirt",
    "紧身衣": "bodysuit",
    "无肩带紧身衣": "strapless leotard",
    "丁字紧身衣": "thong leotard",
    "衣服下紧身衣": "leotard under clothes",
    "紧身衣服": "taut clothes",
    "雪纺连衣裙": "chiffon dress",
    "背心": "tank top",
    "连身裙": "dress",
    "露背连身裙": "backless dress",
    "绕颈连身裙": "halter dress ",
    "毛衣连身裙": "sweater dress",
    "露背装": "backless outfit",
    "毛衣": "sweater",
    "高领毛衣": "turtleneck sweater",
    "罗纹毛衣": "ribbed sweater",
    "露肩毛衣": "off-shoulder sweater",
    "肩膀切口": "shoulder cutout",
    "臀部切口": "hip vent",
    "心型切口": "heart cutout",
    "后背切口": "back cutout",
    "下胸切口": "underboob cutout",
    "束腹": "corset",
    "小可爱露腹短上衣": "crop top",
    "赛车服(By KimZuo)": "racing suit",
    "护士服(By Yao_men)": "nurse",
    "乳胶紧身衣(By Yao_men)": "latex",
    "白大褂(By Yao_men)": "lab_coat",
    "便利店工作服(By 糯米)": "convenience store uniforms",
    "夏日长裙": "summer long skirt",
    "西装": "business suit",
    "浴衣": "yukata",
    "圣诞装": "santa",
    "哥特洛丽塔风格": "gothic_lolita",
    "马猴烧酒风格": "mahou shoujo",
    "女仆装": "Maid dress",
    "西服(black黑)-by bilibili-跑酷": "black suit",
    "頸帶": "neck ribbon",
    "无胸罩": "no_bra",
    "黑丝连体衣": "conjoined black silk",
    "兜帽斗篷": "Cape hood",
    "修女服": "nun clothes",
    "军装": "military_uniform",
    "汉服": "hanfu",
    "破损的衣物": "torn clothes",
    "黑色礼服": "black skirt dress, flower pattern in dress,black gown",
    "披风": "cloak",
    "白色风衣": "white_windbreaker",
    "风衣": "wind coat",
    "奶牛比基尼": "cow_bikini",
    "露背毛衣": "Open-backed sweater",
    "曬痕": "tan line",
    "透明衣服": "see-through",
    "运动制服": "gym_uniform",
    "晚礼服": "evening dress",
    "礼服": "formal dress",
    "战斗服": "combat suit",
    "小披风": "poncho",
    "休闲服(素上衣、牛仔裤)": "casual wear",
    "实验袍": "lab coat",
    "学校制服": "school_uniform",
    "甜美可爱的洛丽塔": "sweet_lolita",
    "网纹衣": "fishnet top",
    "魔女风格服": "Witch dress",
    "巫女服": "Miko clothing",
    "大衣": "overcoat",
    "湿润的衣服": "wet clothes",
    "长袍": "robe",
    "战壕风衣": "trench_coat",
    "抹胸": "strapless tank top, navel cutout",
    "派克大衣": "parka",
    "洛丽塔风格": "lolita_fashion",
    "无内衣": "no underwear",
    "水手裙": "sailor dress",
    "紧身连体衣": "zentai",
    "皮衣": "leather jacket",
    "防弹衣": "bulletproof_vest",
    "蛛网纹路": "spider web print",
    "sweet_lolita": "sweet_lolita",
    "A": "Maid dress",
    "撕裂的衣服": "torn clothes",
    "无": "less clothes",
    "乳胶衣": "latex_bodysuit",
    "中式死库水（辉木）":
        "Chinese style,One-piece swimsuit，Clothes with gold patterns",
    "雨衣": "raincoat",
    "不知火舞": "Mai Shiranui",
    "睡衣": "nightgown",
    "街头风格服饰": "street wear",
    "修女": "loli,one girl,domineering lady, nun",
    "浴袍": "bathrobe",
    "铠甲": "armor",
    "外套": "coat",
    "连帽衫(带帽卫衣)": "hoodie",
    "圆领卫衣": "sweatshirt",
    "蓝白条纹比基尼": "blue and white striped bikini",
    "神父/修生黑袍": "Cassock",
    "动力甲": "power armor",
    "旗袍（效果好）": "cheongsam",
    "工装": " dungarees",
    "透过衣服能看到胸罩": "bra visible through clothes",
    "蕾丝边胸罩": "lace-trimmed bra",
    "一些风格服饰": "indian clothes,chinese clothes,Cleopatra",
    "肚皮舞者": "Belly Dancer",
    "连体白丝": "conjoined white silk",
    "透明水手服": "see-through serafuku",
    "高叉泳衣": "slingshot swimsuit",
    "礼服长裙": "revealing dress",
    "病号服": "hospital gown",
    "白色衣服": "White clothes",
    "希腊服饰": "Greek clothes",
    "紧身连衣裤": "leotards",
    "V领针织毛衣（无袖背心）": "V-NECK SWEATER VEST",
    "南瓜裙": "Pumpkin skirt",
    "万圣节服装": "halloween_costume",
    "软壳外套": "soft shell coat",
    "内衣": "underwear",
    "外骨骼": "exoskeleton",
    "罩衫": "frock",
    "道袍": "Taoist robe",
    "军大衣": "Army overcoat",
    "荷叶边衬衫": "frillded shirt",
    "黑色连衣裙+白色打底T恤搭配(请勿去掉tag括号)":
        "(((black sundress with round neck,white T-shirt bottom)))",
    "外骨骼机甲": "Exoskeleton Mecha",
    "拼接款": "mosaic",
    "战袍": "Battle Robe",
    "机械服装": "mechanical clothes",
    "机械战甲": "[Battle Robe:Exoskeleton Mecha:0.3]",
    "露肩": "cropped shoulders",
    "长袖运动服（直译为立领长风衣）": "Standing collar long windbreaker",
    "无袖衬衫": "sleeveless shirt",
    "方舟风格服装（2019刻板印象）":
        "wind coat,skirt,scarf, gloves, leg belt, arm strap, hairclip",
    "露脐": "navel",
    "OL套装": "office lady suit",
    "足球球衣": "Soccer team jersey",
    "情趣内衣": "hot underware",
    "兔女郎": "Bunny Girl",
    "和服": "kimono",
    "红格衬衫": "Red Plaid Shirts",
    "体操服": "student training wear",
    "开胸毛衣": "open-chest sweater",
    "侧系带比基尼下着": "side-tie bikini bottom",
    "逆兔女郎": "reverse bunny suit",
    "1婚纱": "wedding_dress",
    "军礼服": "Military officer dress",
    "运动胸罩": "sports bra",
    "全套婚纱":
        "bride, bridal veil, bridal gauntlets, wedding dress, bridal garter, bridal legwear, white thighhighs, stiletto heels",
    "黑色冲锋衣": "Black storm jacket",
    "改造巫女服": "nontraditional miko",
    "史莱姆装": "slime dress",
    "啦啦隊": "cheerleading",
    "高叉紧身衣": "highleg leotard",
    "白衬衫": "white shirt",
    "连体服（工作服）": "jumpsuit",
    "穿着红色旗袍(颜色可换)": "wearing white sleeveless cheongsam",
    "校服": "school uniform",
    "印第安服饰": "pocahontas outfit",
    "紧身衬衫": "taut shirt",
    "宇航服（配合科幻标签）": "Space suit",
    "微小比基尼": "micro bikini",
    "中国的衣服裙子": "chinese clothes,china dress",
    "浸湿（如果有内衣会透的更明显）": "soaked",
    "透明的背心": "See-through vest",
    "暴露的衣服": "revealing clothes",
    "透明晚礼服 by czz": "[see-through:evening dress:0.3]",
    "哥特萝莉裙": "gothic lolita，",
    "格子短裙": "plaid skirt",
    "裙子": "skirt",
    "花卉图案连衣裙（白）": "white skirt dress, flower pattern in dress,white gow",
    "花卉图案连衣裙（黑）": "black skirt dress, flower pattern in dress,black gow",
    "夏日连衣裙": "summer dress",
    "紧身连衣裙": "Dirndl",
    "长裙": "Long skirt",
    "雨裙": "Rainskirt",
    "无肩带礼服": "strapless dress",
    "微型短裙": "microskirt",
    "黑百褶裙": "black pleated skirt",
    "盔甲裙": "armored dress",
    "吊带裙": "suspender skirt",
    "【补档】分层群": "layered skirt",
    "围裙": "apron",
    "现代洛丽塔": "lolita fasion",
    "蓬蓬裙": "pettiskirt",
    "腰围裙": "waist apron",
    "哥特式洛丽塔": "lolita gothic",
    "中式旗袍死库水": "chinese clothes+leotard",
    "铅笔裙": "pencil skirt",
    "白色连衣裙": "white skirt",
    "包臀裙": "sheath dress",
    "轻纱广袖裙": "Light gauze wide sleeve skirt，",
    "带褶连衣裙": "pleated dress",
    "睡裙": "night dress",
    "背心裙": "jumper skirt",
    "衬裙": "petticoat",
    "绕颈裙": "halterdress",
    "透明硬纱/蕾丝花边": "Organza lace",
    "迷你裙": "miniskirt",
    "婚纱": "wedding dress",
    "薄沙连衣裙": "sheer tulle dress",
    "连衣裙": "one-piece dress",
    "露肩连衣裙": "off-shoulder dress",
    "半身百褶裙": "pleated skirt",
    "牛仔短裤": "denim shorts",
    "裤子": "pants",
    "内裤": "underpants",
    "吊带裤": "trousers with suspenders",
    "灯笼裤": "bloomers",
    "See-through Pajamas": "See-through Pajamas",
    "兜裆布": "fundoshi",
    "骆驼趾/骆驼肌(紧身效果)": "cameltoe",
    "吊带牛仔裤": "Denim suspenders",
    "紧身裤 ": "leggings",
    "丁字裤": "thong",
    "短裤": "shorts",
    "武士裤": "unbuttoned clothes",
    "高腰裤 （低腰修改为low）": "high-waist pants",
    "红色短裤": "red shorts",
    "瑜伽裤": "yoga pants",
    "西装裤": "trousers",
    "低腰裤 （高腰修改为high）": "low-waist pants",
    "牛仔裤": "jeans"
}
Socks = {
    "膝下袜": "kneehighs",
    "吊袜带": "garter straps garter belt",
    "袜子": "socks",
    "无趾护腿": "toeless legwear",
    "黑丝(By 你不史蒂夫)": "black stocking",
    "连腰吊带袜(By 好人)": "garter_belt",
    "横条袜(By 好人)": "striped_socks",
    "泡泡袜(By 好人)": "loose_socks",
    "长袜(By 好人)": "kneehighs",
    "黑丝条纹质感（随缘生效）":
        "{{{Leg stockings,：Compiled by thin filament lines arranged horizontally}}}，{black stockings}",
    "日本式短布袜": "tabi",
    "黑色裤袜": "black pantyhose",
    "过膝袜（单侧）": "thighhighs_on_one_leg",
    "条纹过膝袜": "striped_thighhighs",
    "黑色过膝袜": "black_thighhighs",
    "white stocking": "white stocking",
    "接缝裤袜": "seamed legwear",
    "过膝袜": "thighhighs",
    "绑腿连裤袜": "thighband pantyhose",
    "巫女袜": "(miko thighhighs)",
    "黑丝": "loli",
    "蕾丝的，后面加东西就行": "lace-trimmed",
    "踩脚袜，马镫裤": "stirrup legwear",
    "裤袜": "pantyhose",
    "边缘系带的日式袜子": "ribbon-trimmed_legwear",
    "拉下裤袜": "pantyhose pull",
    "白丝(By 你不史蒂夫)": "white stocking",
    "网裤袜": "fishnet pantyhose",
    "绿色过膝": "green_thighhighs",
    "白色短袜": "white ankle socks",
    "白裤袜": "white pantyhose",
    "粉色过膝袜(By 好人)": "pink_thighhighs",
    "裹腿(一般为丝袜)": "legwear",
    "精细面料/有质感的(丝袜)": "fine fabric emphasis",
    "白色过膝袜": "white_thighhighs",
    "无裤裆丝袜": " crotchless pantyhose",
    "连身袜": "bodystocking"
}
Shoes = {
    "高跟鞋": "high heels",
    "运动鞋": "sneakers",
    "交叉系带鞋": "cross-laced footwear",
    "靴子": "boots",
    "膝下靴": "knee boots",
    "短靴": "ankle boots",
    "系带靴": "lace-up boots",
    "乐福鞋": "loafers",
    "不穿鞋": "no shoe",
    "拖鞋": "slippers",
    "赤脚": "barefoot",
    "女式学生鞋": "uwabaki",
    "皮鞋": "leather shoes",
    "高跟礼鞋": "High heeled evening shoes",
    "凉鞋": "sandals",
    "高跟凉鞋": "high heeled sandals",
    "木屐": "geta",
    "高跟长筒靴": "High heeled boots",
    "芭蕾舞足尖鞋": "pointe shoes",
    "玛丽珍鞋（猪腰子鞋）": "mary_janes",
    "厚底高跟靴": "platform boots",
    "雨靴": "Rainboots",
    "坡跟鞋": "wedge heels",
    "有带子的高跟鞋": "strappy heels",
    "战术靴": "combat boots",
    "脚铐": "shackles",
    "过膝长靴": "thigh boots",
    "人字拖": "Flip-flops",
    "高跟膝下靴": "high helled low knee boots",
    "露趾高跟鞋": "open toe high",
    "细高跟": "stiletto heels"
}
Gloves = {
    "手套": "gloves ",
    "肘部手套": "elbow gloves",
    "猫猫手套": "paw gloves",
    "无指手套": "fingerless gloves",
    "袖子": "sleeves",
    "分离式袖子": "detached sleeves",
    "宽袖": "wide sleeves",
    "丝带饰边袖子 ": "ribbon-trimmed sleeves",
    "无袖": "sleeveless",
    "手腕袖口": "wrist cuffs",
    "婚礼手套": "bridal gauntlets",
    "拳击手套": "boxing gloves",
    "乳胶手套": "latex gloves",
    "蓬松的大袖子": "puffy sleeves",
    "连指手套": "mittens",
    "蕾丝边手套": "lace-trimmed_gloves",
    "手铐": "handcuffs",
    "战术手套": "Tactical gloves",
    "短袖": "short sleeves",
    "长袖手套": "elbow_gloves",
    "长袖": "Long sleeve",
    "长手套": "long gloves",
    "金属手套": "gauntlets"
}
Kazari = {
    "兔尾": "rabbit tail",
    "吊带": "suspenders",
    "围巾": "scarf",
    "女仆头饰": "maid headdress",
    "腰带": "belt",
    "丝带": "ribbon",
    "发带": "hair ribbon",
    "颈带": "neck ribbon",
    "帽带": "hat ribbon",
    "大腿带": "thigh strap",
    "薄纱面纱": "veil mouth veil",
    "婚礼面纱": "bridal veil",
    "光环": "halo",
    "铃铛": "bell",
    "牛铃": "cowbell",
    "流苏": "tassel",
    "面罩": "mask",
    "发饰": "hair ornament",
    "发环": "hair rings",
    "发花": "hair_flower",
    "蝴蝶结": "hair bow",
    "发簪": "hair stick",
    "兜帽": "hood",
    "护士帽": "nurse cap",
    "皇冠": "crown",
    "贝雷帽": "beret",
    "发卡": "hairband",
    "眼镜": "glasses",
    "太阳镜": "sunglasses",
    "眼罩": "blindfold",
    "眼罩(独眼)": "eyepatch",
    "耳环": "earrings",
    "项圈": "collar",
    "水手领": "sailor collar",
    "项链": "necklace",
    "领结": "bowtie",
    "三重冕": "tiara",
    "伞": "umbrella",
    "粗尾巴": "giant green shark tail",
    "巫师帽": "wizard hat",
    "蝙蝠翅膀": "bat_wing",
    "十字架项链": "cross necklace",
    "手捧花（花嫁）": "Holding the wedding bouquet with both hands",
    "漁夫帽": "fisherman's hat",
    "背包": "backpack",
    "飛行員護目鏡": "FLIGHT Goggles",
    "光剑": "with lightsaber",
    "枪械": "firearms",
    "口罩": "Cold-weather mask",
    "耳机": "headphone",
    "领带": "necktie",
    "棒球帽": "baseball_cap",
    "针织帽": " Knitted hat",
    "海军帽": "naval cap",
    "捷克南瓜燈": " jack-o'-lantern",
    "尾巴": "tail",
    "手杖": "cane",
    "扫把": "broom",
    "额前的发带": "headband",
    "太阳齿轮翅膀(大量齿轮,翅膀更多更乱,效果意外不错": "Wings with sun gears",
    "报童帽": "cabbie_hat",
    "火焰之轮（附着火焰的法轮？）": "The wheel of fire",
    "电线": "wire",
    "天线头饰（类似于碧蓝航线中绫波的头饰）": "antenna hair clips ",
    "书": "book",
    "笔记本电脑": "laptop",
    "御寒耳罩": "earmuffs",
    "口袋": "pockets",
    "纽扣": "buttons",
    "束缚": "shibari",
    "鸭舌帽": "peaked cap",
    "苏联毛帽": "Ushanka",
    "怀表": "pocket watch pendant",
    "防弹背心": "Tactical bulletproof vest",
    "臂环/臂章": "armlet",
    "头链 (参考Wlop风铃公主的头饰，成功率低)": "head chain, jewelry",
    "头纱": "veil",
    "贴颈项链": "choker",
    "阔剑/弯刀/飞刀": "glaive",
    "女巫帽": "Witch_hat",
    "蝴蝶结发饰": "hair_bow",
    "斗篷": "capelet ",
    "绷带": "bandage",
    "口球": "gagged",
    "武士刀": "Samurai Sword",
    "油纸伞": "Oilpaper umbrella",
    "脐钉": "navel piercing",
    "法杖": "wand,magic",
    "狐狸面具": "fox mask",
    "披肩": "capelet",
    "尾巴插入（臀部出现尾巴）": "tail insertion",
    "吉它": "Guitar",
    "狼耳": "wolf ears",
    "发夹": "hairclip",
    "zun帽": "zun hat",
    "翅膀": "wings",
    "魔法帽": "(magic hat)",
    "圣诞帽": "christmas hat",
    "手镯": "bracelet",
    "符文宝石": "A rock with runes",
    "红围巾": "red_scarf",
    "腿环": "garter",
    "铃铛项圈": "bell collar",
    "胸牌": "Badge, Mountain, River, Colorful",
    "波浪帽檐遮阳帽": "Sun hat with wavy brim"
}
