from gath.drawer.GathDrawer import GathDrawer


class LoRAModelMerger:
    def __init__(self, base_model_dir: str, device: str = 'cuda'):
        """

        :param base_model_dir: SD-v1-5, etc.
        :param device: cuda, cpu, etc.
        """
        self.__base_model_dir = base_model_dir
        self.__device = device

    def merge_lora_on_base(
            self,
            lora_model_safetensors_file,
            huggingface_repo_dir,
            multiplier: float = 1.0
    ):
        """

        :param lora_model_safetensors_file: generated by sd-scripts
        :param huggingface_repo_dir:
        :param multiplier:
        :return:
        """
        drawer = GathDrawer.from_pretrained(self.__base_model_dir)
        drawer.to_device(self.__device)
        drawer.load_lora_weights(lora_model_safetensors_file, multiplier, self.__device)
        drawer.save_model(huggingface_repo_dir)


